### ISSUE TITLE
Facing Error while using validate (line ...)  'total dimension of C should be > length(b)'

### ISSUE THREAD

**Issue by SunandanAdhikary** [sqlp/sdpt3#15]
Facing Error using validate (line 143) total dimension of C should be > length(b) while using sdpt3 during Common Lyapunov function constraints. It fails while my total number of constraints becomes almost more than 40. Am I missing something?
Attaching the sample matlab code.
[iterative_controllerSynthOpt.zip](https://github.com/sqlp/sdpt3/files/6168426/iterative_controllerSynthOpt.zip)

**Comment by johanlofberg** [comment]
sdpt3 is sensitive to when models become structurally strange, such as redundantly parameterized as you get. This means it is not a suitable solver to be used inside bmibnb, as bmibnb will generate all kinds of weird models during the branching process. Mosek is a more robust choice

Having said that, the likelihood for solving this model is fairly close to 0, global semidefinite programming just ain't there yet.

Additionally, the model looks weird as you seem to do some kind of robust region of attraction analysis, but you have the initial state as a decision variable. In other words, you are tryin to find *a* state for which the trajectories are fine, instead of the standard problem setup where you prove that something holds for all initial states (possibly in some region). Such a infinite-dimensional analysis is typically based on the use of the S-procedure and more generally sum-of-squares analysis in combination with positivstellensatz etc. Googling "sum-of-squares region of attraction safe set" gives you loads of references on the topic, it was

**Comment by johanlofberg** [comment]
Even more weird is that you have
constraints = [constraints, AA_cl'*P_lyap*AA_cl-P_lyap <= -e*eye(size(P_lyap)), -P_lyap <= -e*eye(size(P_lyap))];

where nothing in the constraint depends on the stuff chaning in the loop.

That is not an issue for this issues tracker though, but an issue for YALMIP google groups.

**Comment by johanlofberg** [comment]
OK, saw that the AA_cl was changed. Anyhow, not an SDPT3 discussion.

**Comment by SunandanAdhikary** [comment]
Yes, I am trying to find a robust gain to reach a certain goal , staying safe. I posted a similar problem in yalmip group as well and thought of posting it here. Thank you for the suggestions. These were so helpful being new and lost in this domain.
